package net.halbear.supernova.registry;

import net.halbear.supernova.SuperNova;
import net.minecraft.particles.ParticleType;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class ModParticles {
    public static final DeferredRegister<ParticleType<?>> PARTICLE_TYPES = DeferredRegister.create(ForgeRegistries.PARTICLE_TYPES, SuperNova.MOD_ID);

    //public static final RegistryObject<BasicParticleType> STAR_SPARKLE = PARTICLE_TYPES.register("star_sparkle", () -> new BasicParticleType(false));
}
