package net.halbear.supernova.registry;

import net.halbear.supernova.SuperNova;
import net.halbear.supernova.entity.Spaceship;
import net.minecraft.entity.EntityClassification;
import net.minecraft.entity.EntityType;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class ModEntities {
    public static DeferredRegister<EntityType<?>> ENTITY_TYPES = DeferredRegister.create(ForgeRegistries.ENTITIES, SuperNova.MOD_ID);

    public static final RegistryObject<EntityType<Spaceship>> SPACESHIP =
            ENTITY_TYPES.register("spaceship", ()-> EntityType.Builder.create(Spaceship::new,
                   EntityClassification.MISC ).size(3f,8f).build(new ResourceLocation(SuperNova.MOD_ID, "spaceship").toString()));
}
